#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

VENV_DIR="${VENV_DIR:-$ROOT_DIR/.venv}"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/tmp/medgemma_evidence}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ 2>/dev/null || echo unknown)"
RUN_DIR="$OUT_DIR/run_${STAMP}"

ensure_venv() {
  if [[ -d "$VENV_DIR" ]]; then
    # shellcheck disable=SC1091
    source "$VENV_DIR/bin/activate"
    return 0
  fi
  python3 -m venv "$VENV_DIR" >/dev/null 2>&1 || true
  # shellcheck disable=SC1091
  source "$VENV_DIR/bin/activate"
  if python -c 'import setuptools' >/dev/null 2>&1; then
    python -m pip install -q -e . >/dev/null 2>&1 || true
  fi
}

echo "[evidence] Writing MedGemma evidence artifacts to: ${RUN_DIR}"
mkdir -p "$RUN_DIR"
ensure_venv >/dev/null

echo "[evidence] 1) Collecting doctor.json (connectivity check; no secrets)..."
python -m clinicaflow.cli doctor > "$RUN_DIR/doctor.json"

echo "[evidence] 2) Verifying the configured reasoning backend is real (non-deterministic) and reachable..."
python - "$RUN_DIR/doctor.json" <<'PY'
import json
import sys

path = sys.argv[1]
payload = json.loads(open(path, encoding="utf-8").read())
rb = payload.get("reasoning_backend") or {}
backend = str(rb.get("backend") or "").strip().lower()
ok = rb.get("connectivity_ok")
err = str(rb.get("connectivity_error") or "").strip()

if backend in {"", "deterministic"}:
    raise SystemExit(
        "ERROR: reasoning backend is deterministic. Configure a real MedGemma endpoint first, e.g.\n"
        "  REQUIRE_MEDGEMMA=1 MEDGEMMA_MODEL='<HF_ID_OR_LOCAL_PATH>' bash scripts/demo_one_click.sh\n"
        "or\n"
        "  USE_FREE_MEDGEMMA=1 REQUIRE_MEDGEMMA=1 bash scripts/demo_one_click.sh"
    )

if ok is not True:
    raise SystemExit(f"ERROR: reasoning backend not reachable (connectivity_ok={ok}). {err}")

print(json.dumps({"backend": backend, "base_url": rb.get("base_url"), "model": rb.get("model")}, indent=2))
PY

echo "[evidence] 3) Deep ping (no PHI)..."
python -m clinicaflow.cli ping --which reasoning --pretty > "$RUN_DIR/ping_reasoning.json" || true

cases=(
  "examples/sample_case.json"
  "examples/urgent_neuro.json"
  "examples/case_report_thunderclap.json"
)

echo "[evidence] 4) Generating audit bundles (redacted + full) for ${#cases[@]} synthetic cases..."
for case_path in "${cases[@]}"; do
  base="$(basename "$case_path" .json)"
  echo "           - ${base}"
  python -m clinicaflow.cli audit --input "$case_path" --out-dir "$RUN_DIR/audit_${base}_redacted" --redact >/dev/null
  python -m clinicaflow.cli audit --input "$case_path" --out-dir "$RUN_DIR/audit_${base}_full" >/dev/null
done

echo "[evidence] 5) Writing summary..."
python - "$RUN_DIR/doctor.json" "$RUN_DIR/README.md" <<'PY'
import json
import sys
from datetime import datetime, timezone

doctor_path, out_path = sys.argv[1], sys.argv[2]
payload = json.loads(open(doctor_path, encoding="utf-8").read())
rb = payload.get("reasoning_backend") or {}

lines = [
    "# MedGemma Evidence Pack (synthetic-only)",
    "",
    "This folder is generated by `bash scripts/capture_medgemma_evidence.sh`.",
    "",
    "- DISCLAIMER: decision support only. Not a diagnosis. No PHI.",
    f"- generated_at_utc: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
    f"- reasoning_backend: {rb.get('backend')}",
    f"- reasoning_base_url: {rb.get('base_url')}",
    f"- reasoning_model: {rb.get('model')}",
    "",
    "## Included artifacts",
    "",
    "- `doctor.json`: environment + connectivity check (no secrets).",
    "- `ping_reasoning.json`: deep ping results (no PHI).",
    "- `audit_*_redacted/`: redacted audit bundles (safe for sharing).",
    "- `audit_*_full/`: full audit bundles (still synthetic-only).",
    "",
    "## How judges can verify quickly",
    "",
    "1) Open `doctor.json` and confirm `reasoning_backend.backend != deterministic` and `connectivity_ok=true`.",
    "2) Open any `audit_*_full/triage_result.json` and confirm the trace includes `multimodal_reasoning`.",
    "",
]

open(out_path, "w", encoding="utf-8").write("\n".join(lines))
PY

echo ""
echo "[evidence] Done."
echo "          Folder: ${RUN_DIR}"
echo "          Tip: share the *redacted* audit bundles (audit_*_redacted/) if needed."
